Fix exit 6 from phase 2 curl

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -109,60 +109,62 @@ node {
         }
     }
 
-    stage("Phase Two Deploy") {
-        def piazza_api_key = "empty"
-        def piazza_url = "https://piazza.${env.PHASE_TWO_PCF_DOMAIN}"
-        withCredentials([[$class: 'StringBinding', credentialsId: "${params.BEACHFRONT_PIAZZA_AUTH_TEXT}", variable: 'TOKEN']]) {
-            def keyCurl = sh(script: """curl -s ${piazza_url}/v2/key -u \"${TOKEN}:\"""", returnStdout: true)
-            piazza_api_key = sh(script: """echo \"${keyCurl}\"|grep -oE '\\w{8}-\\w{4}-\\w{4}-\\w{4}-\\w{12}'""", returnStdout: true).trim()
-            sh """
-              if [ -z $piazza_api_key ]; then
-                echo "No Piazza API key found"
-                exit 1
-              fi
-            """
-        }
-        withEnv([
-          "CF_HOME=.cf"
-        ]) {
-            withCredentials([
-              [$class: 'UsernamePasswordMultiBinding', credentialsId: "${env.PCF_CREDS}", usernameVariable: "CFUSER", passwordVariable: "CFPASS"]
-            ]) {
-                sh """
-                  cf api ${env.PCF_API_ENDPOINT}
-                  cf auth ${CFUSER} ${CFPASS}
-                  cf target -o ${env.PCF_ORG} -s ${env.PHASE_TWO_PCF_SPACE}
-                  cf push ${appName} -f manifest.jenkins.yml --hostname ${appName} -d ${env.PHASE_TWO_PCF_DOMAIN} -b ${env.PYTHON_BUILDPACK_NAME} --no-start -u none
-                  cf set-env ${appName} SPACE ${env.PHASE_TWO_PCF_SPACE}
-                  cf set-env ${appName} DOMAIN ${env.PHASE_TWO_PCF_DOMAIN}
-                  cf set-env ${appName} PZ_API_KEY ${piazza_api_key}
-                  cf set-env ${appName} PZ_ADDR ${piazza_url}
-                """
-
-                try {
-                  sh "cf start ${appName}"
-                } catch (Exception e) {
-                  //sh "cf logs --recent ${appName}"
-                  sh "cf delete ${appName} -f -r"
-                  error("Error during application start. Deleting ${appName} and failing the build.")
-                }
-                sh """
-                  cf api ${env.PCF_API_ENDPOINT}
-                  cf auth ${CFUSER} ${CFPASS}
-                  cf target -o ${env.PCF_ORG} -s ${env.PHASE_TWO_PCF_SPACE}
-                """
-                def legacyAppNames = sh(script: """cf routes | grep \"pzsvc-ndwi \" | awk '{print \$4}'""", returnStdout: true)
-                sh "cf map-route ${appName} ${env.PHASE_TWO_PCF_DOMAIN} --hostname pzsvc-ndwi"
-                // Remove legacy applications
-                for (Object legacyApp : legacyAppNames.trim().tokenize(',')) {
-                    def legacyAppName = legacyApp.toString().trim()
-                    if(legacyAppName != appName) {
-                        sh "cf unmap-route ${legacyAppName} ${env.PHASE_TWO_PCF_DOMAIN} --hostname pzsvc-ndwi"
-                        sh "cf delete -f ${legacyAppName} -r"
-                    }
-                }
-            }
-        }
+    if(params.DEPLOY_PHASE_TWO) {
+      stage("Phase Two Deploy") {
+          def piazza_api_key = "empty"
+          def piazza_url = "https://piazza.${env.PHASE_TWO_PCF_DOMAIN}"
+          withCredentials([[$class: 'StringBinding', credentialsId: "${params.BEACHFRONT_PIAZZA_AUTH_TEXT}", variable: 'TOKEN']]) {
+              def keyCurl = sh(script: """curl -s ${piazza_url}/v2/key -u \"${TOKEN}:\"""", returnStdout: true)
+              piazza_api_key = sh(script: """echo \"${keyCurl}\"|grep -oE '\\w{8}-\\w{4}-\\w{4}-\\w{4}-\\w{12}'""", returnStdout: true).trim()
+              sh """
+                if [ -z $piazza_api_key ]; then
+                  echo "No Piazza API key found"
+                  exit 1
+                fi
+              """
+          }
+          withEnv([
+            "CF_HOME=.cf"
+          ]) {
+              withCredentials([
+                [$class: 'UsernamePasswordMultiBinding', credentialsId: "${env.PCF_CREDS}", usernameVariable: "CFUSER", passwordVariable: "CFPASS"]
+              ]) {
+                  sh """
+                    cf api ${env.PCF_API_ENDPOINT}
+                    cf auth ${CFUSER} ${CFPASS}
+                    cf target -o ${env.PCF_ORG} -s ${env.PHASE_TWO_PCF_SPACE}
+                    cf push ${appName} -f manifest.jenkins.yml --hostname ${appName} -d ${env.PHASE_TWO_PCF_DOMAIN} -b ${env.PYTHON_BUILDPACK_NAME} --no-start -u none
+                    cf set-env ${appName} SPACE ${env.PHASE_TWO_PCF_SPACE}
+                    cf set-env ${appName} DOMAIN ${env.PHASE_TWO_PCF_DOMAIN}
+                    cf set-env ${appName} PZ_API_KEY ${piazza_api_key}
+                    cf set-env ${appName} PZ_ADDR ${piazza_url}
+                  """
+  
+                  try {
+                    sh "cf start ${appName}"
+                  } catch (Exception e) {
+                    //sh "cf logs --recent ${appName}"
+                    sh "cf delete ${appName} -f -r"
+                    error("Error during application start. Deleting ${appName} and failing the build.")
+                  }
+                  sh """
+                    cf api ${env.PCF_API_ENDPOINT}
+                    cf auth ${CFUSER} ${CFPASS}
+                    cf target -o ${env.PCF_ORG} -s ${env.PHASE_TWO_PCF_SPACE}
+                  """
+                  def legacyAppNames = sh(script: """cf routes | grep \"pzsvc-ndwi \" | awk '{print \$4}'""", returnStdout: true)
+                  sh "cf map-route ${appName} ${env.PHASE_TWO_PCF_DOMAIN} --hostname pzsvc-ndwi"
+                  // Remove legacy applications
+                  for (Object legacyApp : legacyAppNames.trim().tokenize(',')) {
+                      def legacyAppName = legacyApp.toString().trim()
+                      if(legacyAppName != appName) {
+                          sh "cf unmap-route ${legacyAppName} ${env.PHASE_TWO_PCF_DOMAIN} --hostname pzsvc-ndwi"
+                          sh "cf delete -f ${legacyAppName} -r"
+                      }
+                  }
+              }
+          }
+      }
     }
     if(!params.SKIP_INTEGRATION_TESTS) {
         stage("Phase Two Integration Tests") {
